import { AppError } from '../utils/AppError.js';
import { PRIORITIES, DEFAULT_PRIORITY, isValidPriority, normalizePriority } from '../utils/priority.js';
import { isValidDateString, normalizeDateString } from '../utils/dates.js';
import { trimString } from '../utils/text.js';

/**
 * Field level validators shared by the todo and note validators.
 *
 * Every function pushes readable `{ field, message }` entries into the `errors`
 * array it receives and returns the normalised value (or a default) so callers
 * can build a clean record even while collecting several problems at once.
 */

export const TITLE_MAX_LENGTH = 120;
export const NOTE_TITLE_MAX_LENGTH = 160;
export const DESCRIPTION_MAX_LENGTH = 1000;
export const NOTE_CONTENT_MAX_LENGTH = 5000;

/** Records a field error once. */
export function addError(errors, field, message) {
  errors.push({ field, message });
}

/** Throws a 400 response when any collected errors exist. */
export function throwIfInvalid(errors, message = 'Request data is invalid') {
  if (errors.length > 0) {
    throw AppError.badRequest(message, errors);
  }
}

/**
 * Fields that are owned by the server. Sending them is treated as a client
 * mistake so clients can never fake an id or a timestamp.
 */
export function rejectServerOwnedFields(body, errors) {
  ['id', 'created_at', 'updated_at'].forEach((field) => {
    if (body[field] !== undefined) {
      addError(errors, field, `"${field}" is generated by the server and cannot be set`);
    }
  });
}

/** Title: required, must be a string, must not be blank. */
export function validateTitle(value, errors, { maxLength = TITLE_MAX_LENGTH, required = true } = {}) {
  if (value === undefined || value === null) {
    if (required) addError(errors, 'title', 'Title is required');
    return required ? '' : undefined;
  }
  if (typeof value !== 'string') {
    addError(errors, 'title', 'Title must be a string');
    return '';
  }

  const trimmed = value.trim();
  if (!trimmed) {
    addError(errors, 'title', 'Title cannot be empty');
    return '';
  }
  if (trimmed.length > maxLength) {
    addError(errors, 'title', `Title must be ${maxLength} characters or fewer`);
    return trimmed.slice(0, maxLength);
  }
  return trimmed;
}

/** Description / content: optional free text. */
export function validateText(
  value,
  errors,
  { field = 'description', maxLength = DESCRIPTION_MAX_LENGTH, label = 'Description' } = {},
) {
  if (value === undefined || value === null) return '';
  if (typeof value !== 'string') {
    addError(errors, field, `${label} must be a string`);
    return '';
  }

  const trimmed = value.trim();
  if (trimmed.length > maxLength) {
    addError(errors, field, `${label} must be ${maxLength} characters or fewer`);
    return trimmed.slice(0, maxLength);
  }
  return trimmed;
}

/** Priority: optional, defaults to "medium". */
export function validatePriority(value, errors, { required = false } = {}) {
  if (value === undefined || value === null || value === '') {
    if (required) {
      addError(errors, 'priority', `Priority must be one of: ${PRIORITIES.join(', ')}`);
      return DEFAULT_PRIORITY;
    }
    return DEFAULT_PRIORITY;
  }

  const normalized = normalizePriority(value);
  if (!isValidPriority(normalized)) {
    addError(errors, 'priority', `Priority must be one of: ${PRIORITIES.join(', ')}`);
    return DEFAULT_PRIORITY;
  }
  return normalized;
}

/** Due date: optional ISO date string, or null for "no due date". */
export function validateDueDate(value, errors) {
  if (value === undefined || value === null || value === '') return null;
  if (!isValidDateString(value)) {
    addError(errors, 'due_date', 'Due date must be a valid ISO date, for example 2030-04-01');
    return null;
  }
  return normalizeDateString(value);
}

/** Completed flag: optional, must be a real boolean when supplied. */
export function validateCompleted(value, errors, { defaultValue = false } = {}) {
  if (value === undefined || value === null) return defaultValue;
  if (typeof value !== 'boolean') {
    addError(errors, 'completed', 'Completed must be a boolean value');
    return defaultValue;
  }
  return value;
}
