import { randomUUID } from 'node:crypto';

/**
 * IDs are always generated by the backend (never by the client) so records stay
 * unique even if a client tries to send its own `id`.
 */
export function generateId() {
  return randomUUID();
}

const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/**
 * Checks that an `:id` route parameter is well formed.
 * A malformed id means the request itself is wrong -> 400.
 * A well formed but unknown id means the record is missing -> 404.
 */
export function isValidId(value) {
  return typeof value === 'string' && UUID_PATTERN.test(value.trim());
}
